import styles from './layout.module.css';
import type { Metadata } from 'next'
import { ReactNode } from 'react';

export const metadata: Metadata = {
  title: 'Candace United',
  description: 'Generated by create next app',
}

type LayoutProps = {
  children: ReactNode;
};

export default function Layout({ children }: LayoutProps) {
  return (
    <div className={styles.container}>
      {children}
    </div>
  );
}
